### ISSUE TITLE
Cannot set a longer BLE name than 5 characters

### ISSUE THREAD

**Issue by trixing** [ecc1/gnarl#11]
First off, custom name is broken, but you probably know that. I have a fix for that upcoming.  I have that 99% working, only that I cannot set a name longer than "GNARL". Which is - what?

If I call ble_svc_gap_device_name_set with a name longer than "GNARL" the function ble_gap_adv_set_fields returns error 3 and everything restarts due to the assertion.

Setting the name to "GNARO" works, "GNARL2" does not work.  According to the spec, this should be a 130 character field.

This is with just this one line changed, and not any of my other custom name changes.

Any idea where to even start searching for the culprit?

**Comment by ecc1** [comment]
There's a hard limit on the size of advertising packets. To get a longer name, we'd have to move to a follow-on scan response with the additional info that doesn't fit in the advertisement. I think I was just too lazy to implement that.

**Comment by trixing** [comment]
The SDK menuconfig says 31 bytes, and the example code in [1] does not seem to have a particular configuration either (it matches the gnarl code pretty closely in fact).

Trying this again I also get error 4 from time to time, which is BLE_HS_EMSGSIZE - which seems to be supporting your theory though, hrm.

[1] https://github.com/espressif/esp-nimble/blob/nimble-1.2.0-idf/apps/bleprph/src/main.c

**Comment by trixing** [comment]
Never mind, got it. Pull request forthcoming.  This is a pretty -- interesting -- library...

**Comment by trixing** [comment]
See https://github.com/ecc1/gnarl/pull/15

**Comment by ecc1** [comment]
Closed with f56d542e0c5518fd006dbb917e7ec72775b594e0
