### ISSUE TITLE
having trouble with the make command

### ISSUE THREAD

**Issue by cmdillon77** [ecc1/gnarl#22]
i'm having trouble withthe make command. If i download the zip file and unzip i can make the project folder. but cannot succesfully run idf.py build. if i clone the git I get a make error but the idf.py build cammand runs but stops compiling at 792/815 so i don't know what i am doing wrong.
any help would be great
![image](https://user-images.githubusercontent.com/52702129/166706651-6700f5f8-0a72-4651-b677-d30594340170.png)

**Comment by ecc1** [comment]
Building GNARL has only been tested on Linux.

**Comment by cmdillon77** [comment]
Thanks Eric. I'll try the Ubuntu on windows, or a raspberry pi running debian as my Linux machine to make the file to flash.Sent from Android deviceOn 5 May 2022 01:28, Eric ***@***.***> wrote:
Building GNARL has only been tested on Linux.
