### ISSUE TITLE
GNARL failed to start with GPIO isr service is not installed

### ISSUE THREAD

**Issue by Andre1ko** [ecc1/gnarl#23]
Hello
There is an issue with GNARL code running on TTGO version 1.
Booting of code failed with:
E (359) gpio: gpio_isr_handler_add(465): GPIO isr service is not installed, call gpio_install_isr_service() first.

IDF version - ESP-IDF v4.4.2-386-gee882708f8

**Comment by ecc1** [comment]
Can you see if this problem occurs with v4.3 of ESP-IDF?

**Comment by Andre1ko** [comment]
Hello
Sorry for a long delay

The same situation with v4.3 of ESP-IDF
D (355) GNARL: enable watchdog with a timeout of 300 seconds
I (355) GNARL: subg_rfspy 2.2
D (365) GNARL: radio version 1.2
D (365) GNARL: frequency set to 868000000 Hz
E (365) gpio: gpio_isr_handler_add(476): GPIO isr service is not installed, call gpio_install_isr_service() first

Thank you

**Comment by ecc1** [comment]
I've updated the main branch to call gpio_install_isr_service() which should fix this issue.
