### ISSUE TITLE
Gnarl medtronic AndroidAPS error

### ISSUE THREAD

**Issue by Andre1ko** [ecc1/gnarl#24]
Hello
There is an issue while configuring Medtronic Pump 722 using gnarl on AndroidAPS.
While it is configuring in AndroidAPS there messages displayed: E (48546) gpio: gpio_install_isr_service(460): GPIO isr service already installed
Full log from start:

ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7308
ho 0 tail 12 room 4
load:0x40078000,len:15052
load:0x40080400,len:3680
entry 0x4008067c
I (32) boot: ESP-IDF v4.3.4-192-gc283d9f1a3 2nd stage bootloader
I (32) boot: compile time 19:47:12
I (32) boot: chip revision: 3
I (35) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (43) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (52) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (62) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  2 factory          factory app      00 00 00010000 00200000
I (95) boot: End of partition table
I (99) boot_comm: chip revision: 3, min. application chip revision: 0
I (106) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=11394h ( 70548) map
I (140) esp_image: segment 1: paddr=000213bc vaddr=3ffbdb60 size=03e78h ( 15992) load
I (147) esp_image: segment 2: paddr=0002523c vaddr=40080000 size=0addch ( 44508) load
I (165) esp_image: segment 3: paddr=00030020 vaddr=400d0020 size=56a60h (354912) map
I (294) esp_image: segment 4: paddr=00086a88 vaddr=4008addc size=0dd7ch ( 56700) load
I (330) boot: Loaded app from partition at offset 0x10000
I (330) boot: Disabling RNG early entropy source...
D (356) GNARL: enable watchdog with a timeout of 300 seconds
I (356) GNARL: subg_rfspy 2.2
D (366) GNARL: radio version 1.2
D (366) GNARL: frequency set to 868000000 Hz
D (366) GNARL: display_loop: op 4 arg 0
D (366) GNARL: starting gnarl_loop
D (996) GNARL: service UUID 0235733b-99c5-4197-b856-69219c2a3845
D (1006) GNARL: read_custom_name from nvs
D (1006) GNARL: set default custom name: GNARL
device address: 78:21:84:88:22:42
D (1056) GNARL: gap_device_name 5 GNARL
D (1066) GNARL: advertising started
I (37116) GNARL: connected
D (37116) GNARL: display_loop: op 0 arg 1
D (37116) GNARL: connection handle 0000
D (37116) GNARL: response count notify handle 000E
D (37116) GNARL: timer tick notify handle 0011
D (37796) GNARL: GAP event 3
D (38286) GNARL: notify 1 for response count
D (38306) GNARL: GAP event 3
D (38416) GNARL: BLE firmware version = ble_rfspy 2.0
data_access: received 2 bytes: 01 02
I (38616) GNARL: CmdGetVersion
send_bytes (14): 73 75 62 67 5F 72 66 73 70 79 20 32 2E 32
D (38616) GNARL: rfspy_command 2, queue length 0
D (38616) GNARL: GAP event 13
D (38616) GNARL: notify for response count 1
data_access: sending 15 bytes: DD 73 75 62 67 5F 72 66 73 70 79 20 32 2E 32
data_access: received 4 bytes: 03 06 0B EE
I (39346) GNARL: CmdUpdateRegister
D (39346) GNARL: update_register: addr 0B value EE
D (39346) GNARL: invalid frequency (87158 Hz)
D (39346) GNARL: send_code DD
D (39356) GNARL: rfspy_command 6, queue length 0
D (39356) GNARL: GAP event 13
D (39356) GNARL: notify for response count 2
data_access: sending 1 bytes: DD
data_access: received 4 bytes: 03 06 0A 2E
I (39926) GNARL: CmdUpdateRegister
D (39926) GNARL: update_register: addr 0A value 2E
D (39926) GNARL: invalid frequency (4399658 Hz)
D (39936) GNARL: send_code DD
D (39936) GNARL: rfspy_command 6, queue length 0
D (39936) GNARL: GAP event 13
D (39946) GNARL: notify for response count 3
data_access: sending 1 bytes: DD
data_access: received 4 bytes: 03 06 09 24
I (40466) GNARL: CmdUpdateRegister
D (40466) GNARL: update_register: addr 09 value 24
I (40466) GNARL: setting frequency to 868399658 Hz
D (40466) GNARL: send_code DD
D (40476) GNARL: rfspy_command 6, queue length 0
D (40476) GNARL: GAP event 13
D (40476) GNARL: notify for response count 4
data_access: sending 1 bytes: DD
data_access: received 4 bytes: 03 06 0C 59
I (40996) GNARL: CmdUpdateRegister
D (40996) GNARL: update_register: addr 0C value 59
D (40996) GNARL: update_register: addr 0C ignored
D (41006) GNARL: send_code DD
D (41006) GNARL: rfspy_command 6, queue length 0
D (41006) GNARL: GAP event 13
D (41016) GNARL: notify for response count 5
data_access: sending 1 bytes: DD
data_access: received 4 bytes: 03 06 0F 62
I (41636) GNARL: CmdUpdateRegister
D (41636) GNARL: update_register: addr 0F value 62
D (41636) GNARL: update_register: addr 0F ignored
D (41636) GNARL: send_code DD
D (41646) GNARL: rfspy_command 6, queue length 0
D (41646) GNARL: GAP event 13
D (41646) GNARL: notify for response count 6
data_access: sending 1 bytes: DD
D (42116) GNARL: display_loop: op 1 arg -60
D (42116) GNARL: phone RSSI = -60
D (42116) GNARL: display_loop: op 3 arg 38
D (42116) GNARL: command time = 38
D (42116) GNARL: display_loop: op 1 arg -62
D (42116) GNARL: phone RSSI = -62
D (42126) GNARL: display_loop: op 3 arg 39
D (42126) GNARL: command time = 39
D (42126) GNARL: display_loop: op 1 arg -60
D (42136) GNARL: phone RSSI = -60
D (42136) GNARL: display_loop: op 3 arg 39
D (42146) GNARL: command time = 39
D (42146) GNARL: display_loop: op 1 arg -59
D (42146) GNARL: phone RSSI = -59
D (42156) GNARL: display_loop: op 3 arg 40
D (42156) GNARL: command time = 40
D (42166) GNARL: display_loop: op 1 arg -115
D (42166) GNARL: phone RSSI = -115
D (42166) GNARL: display_loop: op 3 arg 40
D (42176) GNARL: command time = 40
D (42176) GNARL: display_loop: op 1 arg -60
D (42186) GNARL: phone RSSI = -60
D (42186) GNARL: display_loop: op 3 arg 41
D (42186) GNARL: command time = 41
data_access: received 4 bytes: 03 06 10 1A
I (42216) GNARL: CmdUpdateRegister
D (42216) GNARL: update_register: addr 10 value 1A
D (42216) GNARL: update_register: addr 10 ignored
D (42226) GNARL: send_code DD
D (42226) GNARL: rfspy_command 6, queue length 0
D (42226) GNARL: GAP event 13
D (42236) GNARL: notify for response count 7
D (42236) GNARL: display_loop: op 1 arg -58
D (42246) GNARL: phone RSSI = -58
D (42246) GNARL: display_loop: op 3 arg 41
D (42256) GNARL: command time = 41
data_access: sending 1 bytes: DD
data_access: received 4 bytes: 03 06 11 13
I (42806) GNARL: CmdUpdateRegister
D (42806) GNARL: update_register: addr 11 value 13
D (42806) GNARL: update_register: addr 11 ignored
D (42806) GNARL: send_code DD
D (42816) GNARL: rfspy_command 6, queue length 0
D (42816) GNARL: GAP event 13
D (42816) GNARL: notify for response count 8
D (42826) GNARL: display_loop: op 1 arg -107
D (42826) GNARL: phone RSSI = -107
D (42836) GNARL: display_loop: op 3 arg 42
D (42836) GNARL: command time = 42
data_access: sending 1 bytes: DD
data_access: received 3 bytes: 02 0B 02
I (43336) GNARL: CmdSetSWEncoding
D (43336) GNARL: encoding mode 02
D (43336) GNARL: send_code DD
D (43346) GNARL: rfspy_command 11, queue length 0
D (43346) GNARL: GAP event 13
D (43346) GNARL: notify for response count 9
D (43356) GNARL: display_loop: op 1 arg -61
D (43356) GNARL: phone RSSI = -61
D (43356) GNARL: display_loop: op 3 arg 43
D (43366) GNARL: command time = 43
data_access: sending 1 bytes: DD
data_access: received 21 bytes: 14 05 00 C8 00 00 00 00 00 61 A8 00 00 00 A7 57 65 49 8D 00 BC
I (44266) GNARL: CmdSendAndListen
D (44266) GNARL: send_and_listen: len 19 send_channel 0 repeat_count 200 delay_ms 0
D (44276) GNARL: send_and_listen: listen_channel 0 timeout_ms 25000 retry_count 0
TX: sending 11 bytes: A9 69 56 9A 5D 19 68 D5 55 2E C5
E (48546) gpio: gpio_install_isr_service(460): GPIO isr service already installed
D (48546) GNARL: rfspy_command 5, queue length 0
D (61006) GNARL: timer tick 1
D (61006) GNARL: not notifying for timer tick
D (73546) GNARL: RX: timeout
D (73546) GNARL: send_code AA
D (73546) GNARL: GAP event 13
D (73546) GNARL: notify for response count 10
D (73546) GNARL: display_loop: op 2 arg -127
D (73546) GNARL: pump RSSI = -127
D (73556) GNARL: display_loop: op 1 arg -60
D (73556) GNARL: phone RSSI = -60
D (73556) GNARL: display_loop: op 3 arg 73
D (73566) GNARL: command time = 73

**Comment by ecc1** [comment]
This is a warning message and should not affect operation. Two unrelated libraries need to call gpio_install_isr_service, and I don't know a clean way to make sure only one of them does -- there's no API call to check if it's already been done.
