### ISSUE TITLE
Wakeup failed

### ISSUE THREAD

**Issue by rasinhox1337** [ecc1/gnarl#26]
Hi,
i bought lilygo ttgo lora32 v1.
[link](https://pl.aliexpress.com/item/1005003702938260.html?gatewayAdapt=glo2pol) 
i have pump medtronic 722WW. I build mmtune to check frequency.
I changed MMTUNE_START in pump_config.h to 868000000 and after scanning i have "Best frequency 0Hz". Every attempts end "wakeup failed". What should i do to connect with pump.

**Comment by ecc1** [comment]
What antenna are you using with the TTGO board and how close is it to pump? Do you have RF remote enabled on the pump?

**Comment by rasinhox1337** [comment]
Now its good :)
Sorry, I didn't see that I didn't connect the antenna to the end. 
<3

**Comment by ecc1** [comment]
Glad it's working
