### ISSUE TITLE
Make GNARL work without the OLED display

### ISSUE THREAD

**Issue by trixing** [ecc1/gnarl#3]
I was tiying around with the TTGO boards without a display attached (ordered the wrong version). I can only get it to work by commenting out the display code, like this

https://github.com/trixing/gnarl/commit/6ac7619b15f9bd7a4e78212168c1e3d936f5fbbe

What way could we make the display optional? I'm not exactly sure where it hangs as debugging is somewhat cumbersome.

**Comment by ecc1** [comment]
I think the right approach would be to add some #defines and #ifdefs to
include/module. h to distinguish different modules and their capabilities

**Comment by ecc1** [comment]
Closed with 8a3cbccab74ce0d090709bebcf94773e2f243aeb
