### ISSUE TITLE
UpdateRegister calls should not be reordered

### ISSUE THREAD

**Issue by trixing** [ecc1/gnarl#9]
Loop has a tuneRadio function which repeats to
- set a frequency
- send a command to the pump and record the rssi from the return value
to determine the frequency.
(see https://github.com/ps2/rileylink_ios/blob/master/RileyLinkKit/PumpOpsSession.swift#L901)

If the updateRegister calls get reordered, the result will be not meaningful.  It could also be that a different command is still running. 

Given that the caller is single threaded this shouldn't actually be an issue, but I think the re-ordering could be wrong in such a case.

I noticed this when debugging the GetPacket commands which are running for 4 minutes.

I'm not sure what kind of speed update this optimization should bring in the first place, so I'd suggest to remove it.

(nb. How useful tuneRadio actually is, is another debate, I think center frequency would work just fine).

**Comment by ecc1** [comment]
Closed with ea646d21ab998622716f648c80310933aba1e3bd
